### ISSUE TITLE
Poor performance after adding idf

### ISSUE THREAD

**Issue by willard-yuan** [grapeot/BoW#1]
Hi grapeot,

I tested the **BoW** on Ukbench, and the performance is nice. I added the idf, that is the bow is presented by tf*idf, then I on the same dataset. I found the performance decreased. I also tried to measure the similarity by cosine distance, and the performance is not as good as just using idf.

I wonder if you can give me some advice about this.

**Comment by grapeot** [comment]
I don't really know... Yeah the standard way of using BoW is to add tf*idf. But I didn't implement that part and am not aware of the possible tricks here... :(

**Comment by willard-yuan** [comment]
It's don't matter. Thank you all the same.
